[mysql]
mysql.lithesh.shop

[mongodb]
mongodb.lithesh.shop

[redis]
redis.lithesh.shop

[rabbitmq]
rabbitmq.lithesh.shop

[catalogue]
catalogue.lithesh.shop

[user]
user.lithesh.shop

[cart]
cart.lithesh.shop

[shipping]
shipping.lithesh.shop

[payment]
payment.lithesh.shop

[dispatch]
dispatch.lithesh.shop

[web]
web.lithesh.shop

[localhost]
localhost

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
