[mongodb]
mongodb-dev.lithesh.shop
[catalogue]
catalogue-dev.lithesh.shop
[user]
user-dev.lithesh.shop
[cart]
cart-dev.lithesh.shop
[web]
web-dev.lithesh.shop
[redis]
redis-dev.lithesh.shop
[mysql]
mysql-dev.lithesh.shop
[shipping]
shipping-dev.lithesh.shop
[rabbitmq]
rabbitmq-dev.lithesh.shop
[payment]
payment-dev.lithesh.shop
[dispatch]
dispatch-dev.lithesh.shop
[localhost]
localhost

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
